/**
 * State-specific configurations for the 3D neural network visualization.
 *
 * Each state defines colors, rotation speeds, activation patterns, data
 * packet counts, and per-state transition easing for rich emotional contrast.
 */
import type { OrbState, StateConfig, TransitionConfig } from './types'

export const STATE_CONFIGS: Record<OrbState, StateConfig> = {
    idle: {
        primary: [210, 175, 80],
        secondary: [72, 210, 185],
        tertiary: [160, 140, 90],
        glow: [140, 125, 65],
        nodeFloat: 2.0,
        nodeFloatSpeed: 0.25,
        activationSpeed: 1.2,
        activationMin: 0.08,
        activationMax: 0.35,
        activationPattern: 'gentle',
        connectionAlpha: 0.28,
        pulseSpeed: 0.3,
        particleCount: 8,
        particleSpeed: 0.12,
        particleSize: 1.4,
        glowIntensity: 0.12,
        energy: 0.12,
        nodeSpread: 1.0,
        ringFrequency: 0.05,
        rotationSpeedX: 0.03,
        rotationSpeedY: 0.05,
        rotationSpeedZ: 0.01,
        depthOfField: 0.25,
        dataPacketCount: 0,
        dataPacketSpeed: 0,
    },
    listening: {
        primary: [235, 80, 65],
        secondary: [250, 140, 55],
        tertiary: [210, 90, 50],
        glow: [180, 60, 40],
        nodeFloat: 3.0,
        nodeFloatSpeed: 0.6,
        activationSpeed: 4.5,
        activationMin: 0.18,
        activationMax: 0.88,
        activationPattern: 'wave',
        connectionAlpha: 0.38,
        pulseSpeed: 1.0,
        particleCount: 25,
        particleSpeed: 0.55,
        particleSize: 2.0,
        glowIntensity: 0.3,
        energy: 0.7,
        nodeSpread: 1.15,
        ringFrequency: 0.4,
        rotationSpeedX: 0.06,
        rotationSpeedY: 0.09,
        rotationSpeedZ: 0.02,
        depthOfField: 0.2,
        dataPacketCount: 0,
        dataPacketSpeed: 0,
    },
    thinking: {
        primary: [170, 150, 255],
        secondary: [90, 175, 255],
        tertiary: [140, 200, 240],
        glow: [100, 110, 180],
        nodeFloat: 1.5,
        nodeFloatSpeed: 0.8,
        activationSpeed: 6,
        activationMin: 0.25,
        activationMax: 1.0,
        activationPattern: 'cascade',
        connectionAlpha: 0.55,
        pulseSpeed: 2.2,
        particleCount: 50,
        particleSpeed: 1.5,
        particleSize: 1.8,
        glowIntensity: 0.35,
        energy: 0.95,
        nodeSpread: 0.88,
        ringFrequency: 0.9,
        rotationSpeedX: 0.12,
        rotationSpeedY: 0.18,
        rotationSpeedZ: 0.06,
        depthOfField: 0.15,
        dataPacketCount: 18,
        dataPacketSpeed: 1.8,
    },
    speaking: {
        primary: [46, 210, 120],
        secondary: [100, 235, 165],
        tertiary: [70, 200, 140],
        glow: [40, 150, 90],
        nodeFloat: 2.8,
        nodeFloatSpeed: 0.45,
        activationSpeed: 2.8,
        activationMin: 0.14,
        activationMax: 0.78,
        activationPattern: 'rhythmic',
        connectionAlpha: 0.32,
        pulseSpeed: 0.7,
        particleCount: 22,
        particleSpeed: 0.4,
        particleSize: 2.2,
        glowIntensity: 0.25,
        energy: 0.6,
        nodeSpread: 1.08,
        ringFrequency: 0.35,
        rotationSpeedX: 0.04,
        rotationSpeedY: 0.07,
        rotationSpeedZ: 0.015,
        depthOfField: 0.22,
        dataPacketCount: 0,
        dataPacketSpeed: 0,
    },
    processing: {
        primary: [100, 140, 225],
        secondary: [210, 175, 80],
        tertiary: [150, 160, 200],
        glow: [80, 100, 170],
        nodeFloat: 1.0,
        nodeFloatSpeed: 1.0,
        activationSpeed: 4.0,
        activationMin: 0.18,
        activationMax: 0.95,
        activationPattern: 'systematic',
        connectionAlpha: 0.45,
        pulseSpeed: 1.6,
        particleCount: 35,
        particleSpeed: 1.0,
        particleSize: 1.6,
        glowIntensity: 0.3,
        energy: 0.85,
        nodeSpread: 0.95,
        ringFrequency: 0.6,
        rotationSpeedX: 0.08,
        rotationSpeedY: 0.14,
        rotationSpeedZ: 0.04,
        depthOfField: 0.18,
        dataPacketCount: 8,
        dataPacketSpeed: 1.2,
    },
}

/**
 * Transition configs keyed by destination state.
 * Each has a unique duration and easing curve so every state change
 * feels physically different.
 */
export const TRANSITION_CONFIGS: Record<OrbState, TransitionConfig> = {
    idle:       { duration: 1.2,  easing: 'easeOut' },
    listening:  { duration: 0.45, easing: 'sharp' },
    thinking:   { duration: 0.7,  easing: 'elastic' },
    speaking:   { duration: 0.6,  easing: 'easeInOut' },
    processing: { duration: 0.5,  easing: 'bounce' },
}

/** Glyphs used for thinking-state data packets. */
export const DATA_GLYPHS = [
    '01', '10', '11', 'FF', 'A3', '7E', '>>', '<<',
    '0x', '==', '{}', '[]', '//', '##', '**', '&&',
    'f()', 'AI', 'Qb', 'nn', 'dx', '..', '%%',
]
